### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by BBplux** [asceth/memcached#2]
src/library/memcached.erl:43: syntax error before: '/'
src/library/memcached.erl:53: syntax error before: '/'
src/library/memcached.erl:68: syntax error before: '/'
src/library/memcached.erl:78: syntax error before: '/'
src/library/memcached.erl:93: syntax error before: '/'
src/library/memcached.erl:103: syntax error before: '/'
src/library/memcached.erl:120: syntax error before: '/'
src/library/memcached.erl:143: syntax error before: '/'
src/library/memcached.erl:153: syntax error before: '/'
src/library/memcached.erl:168: syntax error before: '/'

**Comment by asceth** [comment]
Hey @BBplux, I'll be honest I haven't touched erlang in a while and have not updated this library. There may be another library out there that is kept more up to date.
